# Generated by Django 3.2 on 2023-02-12 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebleslist_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inmueble',
            old_name='description',
            new_name='descripcion',
        ),
    ]
