# Generated by Django 3.2 on 2023-02-14 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebleslist_app', '0004_auto_20230214_0300'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Inmueble',
            new_name='Edificacion',
        ),
    ]
