# Generated by Django 3.2 on 2023-02-14 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebleslist_app', '0005_rename_inmueble_edificacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('website', models.URLField(max_length=250)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Empresa',
        ),
    ]
