# Generated by Django 3.2 on 2023-02-18 02:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inmuebleslist_app', '0010_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='comentario_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
