# Generated by Django 3.2 on 2023-02-18 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebleslist_app', '0011_comentario_comentario_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='edificacion',
            name='avg_calificacion',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='edificacion',
            name='number_calificacion',
            field=models.IntegerField(default=0),
        ),
    ]
