# Generated by Django 3.2 on 2023-02-18 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebleslist_app', '0012_auto_20230218_1846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edificacion',
            name='avg_calificacion',
        ),
        migrations.RemoveField(
            model_name='edificacion',
            name='number_calificacion',
        ),
    ]
